export const DEMO_CLIENTS = {
  "demo-sarah-chen": {
    id: "demo-sarah-chen",
    client_name: "Sarah Chen",
    business_name: "Chen IT Consulting",
    business_type: "IT Consulting & Web Development",
    property_address: "45 Collins Street, MELBOURNE VIC 3000",
    taxable_income: 200000,
    age: 42,
    mortgage_balance: 765000,
    property_value: 1080000,
    building_value: 540000,
    bup_percentage: 27,
    hours_per_week: 40,
    weeks_per_year: 48,
    strategy: "SBLB(iii)",
    strategy_name: "SBLB(iii)",
    strategy_description: "SBLB(iii)",
    questionnaire_data: {
      mortgage_interest: 38250,
      council_rates: 4365,
      water_rates: 2052,
      building_insurance: 3285,
      repairs_maintenance: 2520,
      electricity_annual: 3528,
      gas_annual: 1665,
      cleaning_annual: 2106,
      security_annual: 648,
      depreciation: 10800,
    },
  },
  "demo-marcus-thompson": {
    id: "demo-marcus-thompson",
    client_name: "Marcus Thompson",
    business_name: "Thompson Architecture Studio",
    business_type: "Architecture & Design Studio",
    property_address: "78 Park Avenue, SYDNEY NSW 2000",
    taxable_income: 200000,
    age: 48,
    mortgage_balance: 850000,
    property_value: 1200000,
    building_value: 600000,
    bup_percentage: 30,
    hours_per_week: 45,
    weeks_per_year: 48,
    strategy: "HBRS(ii)",
    strategy_name: "HBRS(ii) - Home Business Re-Structure: Stay & Start",
    strategy_description: "Home owner starting a business from existing purchased home",
    questionnaire_data: {
      mortgage_interest: 42500,
      council_rates: 4850,
      water_rates: 2280,
      building_insurance: 3650,
      repairs_maintenance: 2800,
      electricity_annual: 3920,
      gas_annual: 1850,
      cleaning_annual: 2340,
      security_annual: 720,
      depreciation: 12000,
    },
  },
  "demo-jennifer-ormond": {
    id: "demo-jennifer-ormond",
    client_name: "Jennifer Ormond",
    business_name: "Ormond Wealth Management",
    business_type: "Financial Planning & Wealth Management",
    property_address: "156 Queen Street, BRISBANE QLD 4000",
    taxable_income: 250000,
    age: 38,
    mortgage_balance: 1200000,
    property_value: 1850000,
    building_value: 850000,
    bup_percentage: 35,
    hours_per_week: 50,
    weeks_per_year: 50,
    strategy: "HBRS(iii)",
    strategy_name: "HBRS(iii) - Home Business Re-Structure: Extend & Start",
    strategy_description: "HBRS(iii) - Home Business Re-Structure: Extend & Start",
    questionnaire_data: {
      mortgage_interest: 52000,
      council_rates: 5280,
      water_rates: 1980,
      building_insurance: 4200,
      repairs_maintenance: 3500,
      electricity_annual: 4680,
      gas_annual: 2100,
      cleaning_annual: 3120,
      security_annual: 1560,
      depreciation: 17000,
    },
  },
}
